name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Install opam
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          opam init -y --disable-sandboxing

      - name: Install project dependencies
        run: just install

      - name: Build and test
        run: just ci